export default{
    "error_code":0,
    "data":[
        {
            "id":1,
            "title":"首页",
            "rank":1,
            "grade":1,
            "parents_id":0,
            "module":1,
            "contentType":"2",
            "listType":"1",
            "children":[

            ]
        },
        {
            "id":2,
            "title":"部门介绍",
            "rank":2,
            "grade":1,
            "parents_id":0,
            "module":1,
            "contentType":"2",
            "listType":"2",
            "children":[
                {
                    "id":3,
                    "title":"部门分类",
                    "rank":1,
                    "grade":2,
                    "parents_id":2,
                    "module":1,
                    "contentType":"1",
                    "listType":"1",
                    "children":[]
                }
            ]
        },
        {
            "id":4,
            "title":"活动预告",
            "rank":3,
            "grade":1,
            "parents_id":0,
            "module":2,
            "contentType":"2",
            "listType":"2",
            "children":[

            ]
        }
    ],
    "tips":"成功",
}